name: Force Docker Build

on:
  workflow_dispatch:

jobs:
  check_release:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.get_release_version.outputs.release_version }}
    steps:
      - name: Get latest release version
        id: get_release_version
        run: |
          RELEASE_VERSION=$(curl -s https://api.github.com/repos/AUTOMATIC1111/stable-diffusion-webui/releases/latest | jq -r '.tag_name')
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
  build:
    needs: check_release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest a1111 commit hash
        id: a1111ui_hash
        run: |
          A1111UI_HASH=$(curl -s https://api.github.com/repos/AUTOMATIC1111/stable-diffusion-webui/commits/master | jq -r '.sha[:7]')
          echo "A1111UI_HASH=$A1111UI_HASH" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/stable-diffusion-webui:latest
            ghcr.io/${{ env.OWNER_LC }}/stable-diffusion-webui:${{ needs.check_release.outputs.release_version }}
            ghcr.io/${{ env.OWNER_LC }}/stable-diffusion-webui:hash_${{ steps.a1111ui_hash.outputs.A1111UI_HASH }}
